### PR TITLE
#44: init command exits if any step's exit code is not 0

### LINKED ISSUE #44: init command should exit if any step returns a non-zero code
Currently steps of the `init` command can fail but subsequent steps are still carried out. This is strange and confusing behaviour and must be stopped.

### PR DESCRIPTION
**Pull request by kirstyburgoine**
Fixes #44

### CODE REVIEW

File: inc/class-command.php [hunk 1]
```diff
@@ -158,15 +158,23 @@ protected function init( InputInterface $input, OutputInterface $output ) {
 			return;
 		}
 
-		$this->start( $input, $output );
+		$status = $this->start( $input, $output );
+		if ( $status !== 0 ) {
+			$output->writeln( '<info>Virtual machine could not be installed or launched.</>' );
+			return;
```
Comment (roborourke) [inline inc/class-command.php]: Only thing to note here is that if the exit code is not 0 then you need to return it. Not returning anything just sets the default exit code of 0 which is why you see that pattern elsewhere in the method.

File: inc/class-command.php [hunk 2]
```diff
@@ -158,15 +158,23 @@ protected function init( InputInterface $input, OutputInterface $output ) {
...
 		$question = new ConfirmationQuestion( 'Install HTTPS certificate? [Y/n] ', true );
 		if ( ! $questioner->ask( $input, $output, $question ) ) {
 			return;
 		}
 
-		$this->secure( $input, $output );
+		$status = $this->secure( $input, $output );
+		if ( $status !== 0 ) {
+			$output->writeln( '<info>HTTPS certificate could not be installed.</>' );
+			return;
```
Comment (roborourke) [inline inc/class-command.php]: Just need to return that status here too.
